name = "Valhelsia 7"
version = "7.0.0-beta.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "69f4aabdaf30cbb658d4488b2b0adbe77435206d0acd393df2d7ebdd88f7fb6a"

[versions]
minecraft = "1.21"
neoforge = "21.0.149"
