name = "Valhelsia 7"
version = "7.0.0-beta.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "1649ba742dfb1717fd6b34a93f4e96ecbe79d551b6809d3cb27976ebf8b82237"

[versions]
minecraft = "1.21"
neoforge = "21.0.163"
