
#General settings
[general]
	#The CurseForge project ID for the modpack
	#Range: > 0
	modpackProjectID = 1044895
	#The name of the modpack
	modpackName = "Valhelsia 7"
	#The version of the modpack
	modpackVersion = "7.0.1"
	#Use the metadata.json to determine the modpack version
	#ONLY ENABLE THIS IF YOU KNOW WHAT YOU ARE DOING
	useMetadata = false

